# Generated by Django 4.2 on 2023-06-23 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads_for_sale', '0002_replies_date_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='replies',
            name='viewed',
            field=models.BooleanField(default=False),
        ),
    ]
