# Generated by Django 4.2 on 2023-07-18 17:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ads_for_sale', '0003_replies_viewed'),
    ]

    operations = [
        migrations.AddField(
            model_name='replies',
            name='accepted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='replies',
            name='ad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ads_for_sale.ads', verbose_name='Объявление'),
        ),
        migrations.AlterField(
            model_name='replies',
            name='text',
            field=models.TextField(verbose_name='Текст'),
        ),
    ]
